INSERT INTO generic_words VALUES ('the');
INSERT INTO generic_words VALUES ('and');
INSERT INTO generic_words VALUES ('an');
INSERT INTO generic_words VALUES ('is');
INSERT INTO generic_words VALUES ('of');
INSERT INTO generic_words VALUES ('in');

INSERT INTO body (word, spam_count, real_count) VALUES ('foo', 30, 2);
INSERT INTO sender (word, spam_count, real_count) VALUES ('sex', 10, 1);
INSERT INTO subject (word, spam_count, real_count) VALUES ('sex', 10, 1);
INSERT INTO body (word, spam_count, real_count) VALUES ('sex', 10, 1);
INSERT INTO body (word, spam_count, real_count) VALUES ('hey', 8, 5);
INSERT INTO sender (word, spam_count, real_count) VALUES ('buddy', 10, 1);
INSERT INTO subject (word, spam_count, real_count) VALUES ('buddy', 10, 5);
INSERT INTO body (word, spam_count, real_count) VALUES ('buddy', 10, 8);
INSERT INTO subject (word, spam_count, real_count) VALUES ('nadine', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('left', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('couple', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('of', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('words', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('in', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('her', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('message', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('for', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('you', 2, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('here', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('job', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('opportunity', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('requested', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('most', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('amazing', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('trading', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('system', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('i', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('have', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('ever', 1, 0);
INSERT INTO subject (word, spam_count, real_count) VALUES ('seen', 1, 0);